name: signal_lab
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+4

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_inappwebview: ^6.0.0
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_fonts: ^6.1.0
  dotted_border: ^2.0.0+2
  flutter_svg: ^2.0.10+1
  flutter_svg_provider: ^1.0.3
  lottie: ^3.1.0
#  carousel_slider: ^4.2.1
  flutter_carousel_slider: ^1.1.0
  shared_preferences: ^2.0.13
  path_provider: ^2.0.9
  intl: ^0.19.0
  pin_code_fields: ^8.0.1
  webview_flutter: ^4.7.0
  url_launcher: ^6.0.20
  flutter_widget_from_html: ^0.14.11
  font_awesome_flutter: ^10.7.0
  animated_bottom_navigation_bar: ^1.3.3
  auto_size_text: ^3.0.0
  simple_animations: ^5.0.2
  firebase_messaging: ^14.7.17
  firebase_core: ^2.25.5
  awesome_dialog: ^3.0.2
  firebase_core_platform_interface: ^5.0.0
  permission_handler: ^11.3.0
  http: ^1.2.0
  flutter_local_notifications: ^17.2.3
  smooth_page_indicator: ^1.1.0
  html: ^0.15.4
  change_app_package_name: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
