// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBljTj1CWUIykMWk_JwoImVGVdC_Q2aQNk',
    appId: '1:465371499504:android:f9bed6ca584219535aab35',
    messagingSenderId: '465371499504',
    projectId: 'alwegdany-afec6',
    storageBucket: 'alwegdany-afec6.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCujclnxMcVSmuxiJgoWpVeZ7rHGVwWnl0',
    appId: '1:465371499504:web:7fc8947492e9a4995aab35',
    messagingSenderId: '465371499504',
    projectId: 'alwegdany-afec6',
    authDomain: 'alwegdany-afec6.firebaseapp.com',
    storageBucket: 'alwegdany-afec6.appspot.com',
    measurementId: 'G-TSPKDYEGWT',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-oj-Xsslsyx4QcvLUFqTkSv2tA5yFZIo',
    appId: '1:465371499504:ios:097541ce21b4a9235aab35',
    messagingSenderId: '465371499504',
    projectId: 'alwegdany-afec6',
    storageBucket: 'alwegdany-afec6.appspot.com',
    iosBundleId: 'com.stackwise.alwegdany',
  );

}